# Generated by Django 3.1.5 on 2021-03-03 08:59

import CCC.Helper.DateHelper
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_start_time', models.DateTimeField(blank=True, default=CCC.Helper.DateHelper.default_start_time, verbose_name='build start time')),
                ('branch', models.CharField(max_length=100)),
                ('assignee', models.CharField(default='unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('hash_value', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CCC.job')),
            ],
        ),
    ]
