# Generated by Django 3.1.5 on 2021-02-11 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='build_start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='build start time'),
        ),
    ]
