# Generated by Django 3.1.5 on 2021-03-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='gerrit_status',
            field=models.CharField(default='Ready', max_length=100),
        ),
    ]
