# Generated by Django 3.1.5 on 2021-03-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCC', '0003_job_jira_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='register',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
